-- migrate:up
CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  kakao_id BIGINT NOT NULL,
  email VARCHAR(255) NULL UNIQUE,
  user_name VARCHAR(255) NULL,
  cellphone VARCHAR(250) NULL,
  profile_image_url VARCHAR(255) NULL,
  sex VARCHAR(100) NULL,
  bio VARCHAR(1000) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL
);

-- migrate:down
DROP TABLE users;
